import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vitest/config';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
	plugins: [
		sveltekit(),
		VitePWA({
			registerType: 'autoUpdate',
			injectRegister: 'script',
			// Use generateSW strategy so Workbox generates the sw from workbox config
			strategies: 'generateSW',
			workbox: {
				// Cache-first for static assets (JS, CSS, images, fonts)
				runtimeCaching: [
					{
						urlPattern: /\.(?:js|css|woff2?|ttf|otf|eot)$/i,
						handler: 'CacheFirst',
						options: {
							cacheName: 'static-assets',
							expiration: {
								maxEntries: 100,
								maxAgeSeconds: 60 * 60 * 24 * 30 // 30 days
							}
						}
					},
					{
						// Cache-first for DAWG binary word list
						urlPattern: /\/words\.dawg$/i,
						handler: 'CacheFirst',
						options: {
							cacheName: 'word-list',
							expiration: {
								maxEntries: 5,
								maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
							}
						}
					},
					{
						// Network-first for dynamic data (future: leaderboards, daily puzzle metadata)
						urlPattern: /\/api\//i,
						handler: 'NetworkFirst',
						options: {
							cacheName: 'dynamic-data',
							networkTimeoutSeconds: 5,
							expiration: {
								maxEntries: 50,
								maxAgeSeconds: 60 * 60 * 24 // 1 day
							}
						}
					}
				],
				// Precache all static assets generated by Vite
				globPatterns: ['**/*.{js,css,html,svg,png,ico,woff,woff2}'],
				// Offline fallback
				navigateFallback: '/',
				navigateFallbackDenylist: [/^\/api\//]
			},
			manifest: false // manifest is already in static/manifest.webmanifest
		})
	],
	test: {
		include: ['src/**/*.{test,spec}.{js,ts}', 'scripts/**/*.{test,spec}.{js,ts}'],
		environment: 'node',
		coverage: {
			provider: 'v8',
			reporter: ['text', 'lcov'],
			include: ['src/lib/**/*.ts']
		}
	}
});
